import { useState, useCallback } from 'react'
import { Download, FileText, File, X, Loader, Check } from 'lucide-react'
import './ExportResult.css'

function ExportResult({
    title,
    result,
    resultUnit,
    resultDetails,
    fullContent, // New prop for full AI content
    onClose
}) {
    const [exporting, setExporting] = useState(false)
    const [exported, setExported] = useState(false)
    const [exportType, setExportType] = useState(null)

    // Get the full content to export
    const getExportContent = useCallback(() => {
        let content = `${title}\n${'='.repeat(title.length)}\n\n`

        // If fullContent is provided (for AI tools), use it
        if (fullContent) {
            content += fullContent
        } else {
            // For calculators, build from result and details
            if (result) {
                content += `Result: ${result}${resultUnit ? ' ' + resultUnit : ''}\n\n`
            }

            // Handle resultDetails - could be string, array, or React element
            if (resultDetails) {
                if (typeof resultDetails === 'string') {
                    content += resultDetails
                } else if (Array.isArray(resultDetails)) {
                    content += 'Details:\n'
                    resultDetails.forEach(detail => {
                        if (detail.label && detail.value) {
                            content += `  • ${detail.label}: ${detail.value}\n`
                        } else if (typeof detail === 'string') {
                            content += `  • ${detail}\n`
                        }
                    })
                }
            }
        }

        content += `\n\n---\nGenerated by Plainly Tools\nhttps://plainly.live${window.location.pathname}\nDate: ${new Date().toLocaleString()}`

        return content
    }, [title, result, resultUnit, resultDetails, fullContent])

    // Export as text file
    const exportAsText = useCallback(() => {
        setExporting(true)
        setExportType('text')

        try {
            const content = getExportContent()

            const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
            const url = URL.createObjectURL(blob)
            const link = document.createElement('a')
            link.download = `${title.toLowerCase().replace(/\s+/g, '-')}-result.txt`
            link.href = url
            link.click()
            URL.revokeObjectURL(url)

            setExported(true)
            setTimeout(() => {
                setExported(false)
                setExporting(false)
                setExportType(null)
            }, 2000)

        } catch (err) {
            console.error('Export failed:', err)
            setExporting(false)
            setExportType(null)
        }
    }, [title, getExportContent])

    // Export as PDF
    const exportAsPDF = useCallback(() => {
        setExporting(true)
        setExportType('pdf')

        try {
            const content = getExportContent()

            // Create a new window for printing as PDF
            const printWindow = window.open('', '_blank')

            if (!printWindow) {
                alert('Please allow pop-ups to export as PDF')
                setExporting(false)
                setExportType(null)
                return
            }

            // Format content with proper HTML/CSS for PDF
            const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <title>${title} - Plainly Tools</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', system-ui, sans-serif;
            padding: 40px;
            line-height: 1.6;
            color: #1a1a1a;
            background: #fff;
        }
        .header {
            border-bottom: 2px solid #a78bfa;
            padding-bottom: 16px;
            margin-bottom: 24px;
        }
        h1 {
            font-size: 28px;
            color: #1a1a1a;
            margin-bottom: 8px;
        }
        .result-box {
            background: linear-gradient(135deg, #f5f3ff 0%, #ede9fe 100%);
            border: 1px solid #a78bfa;
            border-radius: 12px;
            padding: 24px;
            margin: 20px 0;
        }
        .result-label {
            font-size: 14px;
            color: #666;
            margin-bottom: 8px;
        }
        .result-value {
            font-size: 32px;
            font-weight: bold;
            color: #7c3aed;
        }
        .result-unit {
            font-size: 20px;
            color: #9f7aea;
        }
        .content {
            white-space: pre-wrap;
            font-size: 14px;
            line-height: 1.8;
            margin: 20px 0;
            padding: 20px;
            background: #f9fafb;
            border-radius: 8px;
            border: 1px solid #e5e7eb;
        }
        .footer {
            margin-top: 40px;
            padding-top: 16px;
            border-top: 1px solid #e5e7eb;
            font-size: 12px;
            color: #666;
        }
        .footer a {
            color: #7c3aed;
            text-decoration: none;
        }
        @media print {
            body { padding: 20px; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>${title}</h1>
    </div>
    
    ${result ? `
    <div class="result-box">
        <div class="result-label">Result</div>
        <div class="result-value">${result} ${resultUnit ? `<span class="result-unit">${resultUnit}</span>` : ''}</div>
    </div>
    ` : ''}
    
    <div class="content">${(fullContent || (typeof resultDetails === 'string' ? resultDetails : '')).replace(/\n/g, '<br>')}</div>
    
    <div class="footer">
        <p>Generated by <a href="https://plainly.live">Plainly Tools</a></p>
        <p>${new Date().toLocaleString()}</p>
    </div>
    
    <script>
        window.onload = function() {
            window.print();
            setTimeout(function() { window.close(); }, 500);
        }
    </script>
</body>
</html>`

            printWindow.document.write(htmlContent)
            printWindow.document.close()

            setExported(true)
            setTimeout(() => {
                setExported(false)
                setExporting(false)
                setExportType(null)
            }, 2000)

        } catch (err) {
            console.error('Export failed:', err)
            setExporting(false)
            setExportType(null)
        }
    }, [title, result, resultUnit, resultDetails, fullContent, getExportContent])

    // Preview content for display
    const previewContent = fullContent
        ? fullContent.substring(0, 200) + (fullContent.length > 200 ? '...' : '')
        : (typeof resultDetails === 'string'
            ? resultDetails.substring(0, 200) + (resultDetails.length > 200 ? '...' : '')
            : `${result || ''}${resultUnit ? ' ' + resultUnit : ''}`)

    return (
        <div className="export-modal-overlay" onClick={onClose}>
            <div className="export-modal" onClick={e => e.stopPropagation()}>
                <button className="export-modal-close" onClick={onClose}>
                    <X size={18} />
                </button>

                <div className="export-modal-header">
                    <Download size={24} className="export-modal-icon" />
                    <h3>Export Result</h3>
                    <p>Download your result as a file</p>
                </div>

                {/* Preview */}
                <div className="export-preview">
                    <div className="export-preview-card">
                        <span className="export-preview-title">{title}</span>
                        <div className="export-preview-content">
                            {previewContent}
                        </div>
                        <span className="export-preview-brand">plainly.live</span>
                    </div>
                </div>

                {/* Export Options */}
                <div className="export-options">
                    <button
                        className={`export-option ${exported && exportType === 'text' ? 'success' : ''}`}
                        onClick={exportAsText}
                        disabled={exporting}
                    >
                        {exporting && exportType === 'text' ? (
                            <Loader size={20} className="spinner" />
                        ) : exported && exportType === 'text' ? (
                            <Check size={20} />
                        ) : (
                            <FileText size={20} />
                        )}
                        <div className="export-option-text">
                            <span className="export-option-title">
                                {exported && exportType === 'text' ? 'Downloaded!' : 'Save as Text'}
                            </span>
                            <span className="export-option-desc">Plain text file (.txt)</span>
                        </div>
                    </button>

                    <button
                        className={`export-option ${exported && exportType === 'pdf' ? 'success' : ''}`}
                        onClick={exportAsPDF}
                        disabled={exporting}
                    >
                        {exporting && exportType === 'pdf' ? (
                            <Loader size={20} className="spinner" />
                        ) : exported && exportType === 'pdf' ? (
                            <Check size={20} />
                        ) : (
                            <File size={20} />
                        )}
                        <div className="export-option-text">
                            <span className="export-option-title">
                                {exported && exportType === 'pdf' ? 'Downloaded!' : 'Save as PDF'}
                            </span>
                            <span className="export-option-desc">Print to PDF format</span>
                        </div>
                    </button>
                </div>
            </div>
        </div>
    )
}

export default ExportResult
