import { useState, useRef, useCallback } from 'react'
import { Download, Image, FileText, X, Loader, Check } from 'lucide-react'
import './ExportResult.css'

function ExportResult({
    title,
    result,
    resultUnit,
    resultDetails,
    onClose
}) {
    const [exporting, setExporting] = useState(false)
    const [exported, setExported] = useState(false)
    const [exportType, setExportType] = useState(null)
    const previewRef = useRef(null)

    // Generate the result card as an image using Canvas
    const exportAsImage = useCallback(async () => {
        setExporting(true)
        setExportType('image')

        try {
            // Create canvas
            const canvas = document.createElement('canvas')
            const ctx = canvas.getContext('2d')

            // Set dimensions
            const width = 600
            const height = 400
            const dpr = window.devicePixelRatio || 2

            canvas.width = width * dpr
            canvas.height = height * dpr
            ctx.scale(dpr, dpr)

            // Background gradient
            const gradient = ctx.createLinearGradient(0, 0, width, height)
            gradient.addColorStop(0, '#1a1a2e')
            gradient.addColorStop(1, '#16213e')
            ctx.fillStyle = gradient
            ctx.fillRect(0, 0, width, height)

            // Border
            ctx.strokeStyle = '#333'
            ctx.lineWidth = 2
            ctx.strokeRect(1, 1, width - 2, height - 2)

            // Title
            ctx.fillStyle = '#ffffff'
            ctx.font = 'bold 24px Inter, system-ui, sans-serif'
            ctx.textAlign = 'center'
            ctx.fillText(title, width / 2, 60)

            // Result value
            ctx.fillStyle = '#a78bfa'
            ctx.font = 'bold 72px Inter, system-ui, sans-serif'
            ctx.fillText(`${result}${resultUnit ? ' ' + resultUnit : ''}`, width / 2, 180)

            // Result details
            if (resultDetails && resultDetails.length > 0) {
                ctx.fillStyle = '#888888'
                ctx.font = '16px Inter, system-ui, sans-serif'
                let yOffset = 240
                resultDetails.slice(0, 4).forEach(detail => {
                    ctx.fillText(`${detail.label}: ${detail.value}`, width / 2, yOffset)
                    yOffset += 30
                })
            }

            // Branding
            ctx.fillStyle = '#666666'
            ctx.font = '14px Inter, system-ui, sans-serif'
            ctx.fillText('plainly.live', width / 2, height - 30)

            // Download
            const link = document.createElement('a')
            link.download = `${title.toLowerCase().replace(/\s+/g, '-')}-result.png`
            link.href = canvas.toDataURL('image/png')
            link.click()

            setExported(true)
            setTimeout(() => {
                setExported(false)
                setExporting(false)
                setExportType(null)
            }, 2000)

        } catch (err) {
            console.error('Export failed:', err)
            setExporting(false)
            setExportType(null)
        }
    }, [title, result, resultUnit, resultDetails])

    // Export as text file
    const exportAsText = useCallback(() => {
        setExporting(true)
        setExportType('text')

        try {
            let content = `${title}\n${'='.repeat(title.length)}\n\n`
            content += `Result: ${result}${resultUnit ? ' ' + resultUnit : ''}\n\n`

            if (resultDetails && resultDetails.length > 0) {
                content += 'Details:\n'
                resultDetails.forEach(detail => {
                    content += `  • ${detail.label}: ${detail.value}\n`
                })
                content += '\n'
            }

            content += `\nGenerated by Plainly Tools\nhttps://plainly.live${window.location.pathname}\n`
            content += `Date: ${new Date().toLocaleDateString()}`

            const blob = new Blob([content], { type: 'text/plain' })
            const url = URL.createObjectURL(blob)
            const link = document.createElement('a')
            link.download = `${title.toLowerCase().replace(/\s+/g, '-')}-result.txt`
            link.href = url
            link.click()
            URL.revokeObjectURL(url)

            setExported(true)
            setTimeout(() => {
                setExported(false)
                setExporting(false)
                setExportType(null)
            }, 2000)

        } catch (err) {
            console.error('Export failed:', err)
            setExporting(false)
            setExportType(null)
        }
    }, [title, result, resultUnit, resultDetails])

    return (
        <div className="export-modal-overlay" onClick={onClose}>
            <div className="export-modal" onClick={e => e.stopPropagation()}>
                <button className="export-modal-close" onClick={onClose}>
                    <X size={18} />
                </button>

                <div className="export-modal-header">
                    <Download size={24} className="export-modal-icon" />
                    <h3>Export Result</h3>
                    <p>Save your calculation result</p>
                </div>

                {/* Preview Card */}
                <div className="export-preview" ref={previewRef}>
                    <div className="export-preview-card">
                        <span className="export-preview-title">{title}</span>
                        <span className="export-preview-result">
                            {result}{resultUnit && <span className="export-preview-unit">{resultUnit}</span>}
                        </span>
                        {resultDetails && resultDetails.length > 0 && (
                            <div className="export-preview-details">
                                {resultDetails.slice(0, 3).map((detail, i) => (
                                    <div key={i} className="export-preview-detail">
                                        <span>{detail.label}:</span>
                                        <span>{detail.value}</span>
                                    </div>
                                ))}
                            </div>
                        )}
                        <span className="export-preview-brand">plainly.live</span>
                    </div>
                </div>

                {/* Export Options */}
                <div className="export-options">
                    <button
                        className={`export-option ${exported && exportType === 'image' ? 'success' : ''}`}
                        onClick={exportAsImage}
                        disabled={exporting}
                    >
                        {exporting && exportType === 'image' ? (
                            <Loader size={20} className="spinner" />
                        ) : exported && exportType === 'image' ? (
                            <Check size={20} />
                        ) : (
                            <Image size={20} />
                        )}
                        <div className="export-option-text">
                            <span className="export-option-title">
                                {exported && exportType === 'image' ? 'Downloaded!' : 'Save as Image'}
                            </span>
                            <span className="export-option-desc">PNG format, perfect for sharing</span>
                        </div>
                    </button>

                    <button
                        className={`export-option ${exported && exportType === 'text' ? 'success' : ''}`}
                        onClick={exportAsText}
                        disabled={exporting}
                    >
                        {exporting && exportType === 'text' ? (
                            <Loader size={20} className="spinner" />
                        ) : exported && exportType === 'text' ? (
                            <Check size={20} />
                        ) : (
                            <FileText size={20} />
                        )}
                        <div className="export-option-text">
                            <span className="export-option-title">
                                {exported && exportType === 'text' ? 'Downloaded!' : 'Save as Text'}
                            </span>
                            <span className="export-option-desc">Plain text file for records</span>
                        </div>
                    </button>
                </div>
            </div>
        </div>
    )
}

export default ExportResult
